import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
//import postcss from 'rollup-plugin-postcss'
import sassPostcss from '@koffeine/rollup-plugin-sass-postcss';
import autoprefixer from 'autoprefixer';
import reporter from 'postcss-reporter';
//import doiuse from 'doiuse';
import { uglify } from 'rollup-plugin-uglify';
import copy from 'rollup-plugin-copy';
import del from 'rollup-plugin-delete';
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

const dev = process.env.PRODUCTION_MODE === undefined;

export default {
  input: "./module/zweihander.js",
  output: {
    dir: dev ? "." : "./dist/",
    sourcemap: true,
    sourcemapExcludeSources: dev,
    format: "es",
    banner
  },
  plugins: [
    nodeResolve(),
    commonjs(),
    sassPostcss({
      include: [/\.scss/u, /\.css/u],
      exclude: undefined,
      sourcemap: true,
      output: 'zweihander.css',
      plugins: [
        require('colorguard'),
        autoprefixer(),
        // doiuse({browsers: ['> 1.5% and last 3 versions']}),
        require('postcss-assets')({
          loadPaths: ['assets/'],
          relative: '.'
        }),
        reporter({ clearReportedMessages: true })
      ]
    }),
    // postcss({
    //   sourceMap: true,
    //   extract: true,
    //   minimize: !dev,
    //   plugins: [
    //     require('colorguard'),
    //     autoprefixer(),
    //     // doiuse({browsers: ['> 1.5% and last 3 versions']}),
    //     require('postcss-assets')({
    //       loadPaths: ['assets/'],
    //       relative: '.'
    //     }),
    //     reporter({ clearReportedMessages: true })
    //     ]
    // }),
    !dev && uglify(),
    !dev && del({targets: 'dist'}),
    !dev && copy({
      targets: [
        {src: ['./*','!./.*','!node_modules','!module','!system.template.json','!rollup.config.js','!yarn-error.log','!readme-assets'], dest: 'dist'}
      ]
    })
  ]
};
