/**
 * Define a set of template paths to pre-load
 * Pre-loaded templates are compiled and cached for fast access when rendering
 * @returns {Promise}
 */

export const preloadHandlebarsTemplates = async function () {
  const $$ = (path) => 'systems/zweihander/templates/' + path + '.hbs';
  return loadTemplates([
    $$('character/tab-main'),
    $$('character/header'),
    $$('item/ancestry'),
    $$('item/armor'),
    $$('item/condition'),
    $$('item/disease'),
    $$('item/disorder'),
    $$('item/drawback'),
    $$('item/injury'),
    $$('item/profession'),
    $$('item/ritual'),
    $$('item/skill'),
    $$('item/spell'),
    $$('item/talent'),
    $$('item/taint'),
    $$('item/trait'),
    $$('item/trapping'),
    $$('item/quality'),
    $$('item/uniqueAdvance'),
    $$('item/weapon'),
    $$('item-card/item-card-spell'),
    $$('item-card/item-card-weapon'),
    $$('item-card/item-card-profession'),
    $$('item-summary/trapping'),
    $$('item-summary/weapon'),
    $$('item-summary/armor'),
    $$('item-summary/spell'),
    $$('item-summary/ritual'),
    $$('item-summary/condition'),
    $$('item-summary/disorder'),
    $$('item-summary/disease'),
    $$('item-summary/injury'),
    $$('item-summary/taint'),
    $$('item-summary/profession'),
    $$('item-summary/trait'),
    $$('item-summary/talent'),
    $$('item-summary/drawback'),
    $$('item-summary/uniqueAdvance'),
    $$('item-summary/effect'),
    $$('partials/items-list'),
    $$('partials/skills-list'),
    $$('character/currency'),
    $$('character/encumbrance-meter'),
    $$('character/magick-skill-selector'),
    $$('partials/modded-value'),
    $$('partials/focuses-list'),
    $$('partials/detail-item-wrapper'),
    $$('partials/detail-languages'),
    $$('partials/detail-risk-factor'),
    $$('partials/details-list'),
  ]);
};
